### PR TITLE
Adding travis build and info badges

### PR DESCRIPTION
**Pull request by matzew**
@wtrocki Travis

### CODE REVIEW

**Comment by matzew** [comment]
some weirdness going on w/ dependencys and java versions...

will check later

**Comment by wtrocki** [comment]
Love it! It looks now like typical open source repo! Thanks a lot for doing this!

**Comment by wtrocki** [comment]
Retest this please

**Comment by wtrocki** [comment]
Rebased - still failing :(

**Comment by matzew** [comment]
hehe

**Pull request merged**
