### PR TITLE
RHMAP-15628 build history

### PR DESCRIPTION
**Pull request by aliok**
2 commits:
- Renamed some classes
- Implemented get build history functionality

### CODE REVIEW

**Comment by aliok** [comment]
How to verify:
Step 1. Run tests 😎  `mvn test`
Step 2. Use this code
```
DiggerClient client = DiggerClient.createDefaultWithAuth("HOST", "USERNAME", "PASSWORD");
final List<BuildWithDetails> buildHistory = client.getBuildHistory("JOB-NAME");
    for (BuildWithDetails buildWithDetails : buildHistory) {
    System.out.println(buildWithDetails.getNumber() + " " + buildWithDetails.getResult());
}
```

**Review by aidenkeating — APPROVED** [review]
LGTM! 👍 Do we need a version bump?

**Comment by aliok** [comment]
@aidenkeating very good question.
Normally, in an open source project like this, we would use snapshots for testing stuff. Version would only be increased with a release. But now that this thing is gonna be integrated with RHMAP, people might have other ideas.

@wei-lee @odra what do you think guys?

wdyt @matzew ?

**Comment by odra** [comment]
IMHO we should create a release tag/bump version once we have finished a feature or a set of features.

Currently, I think we could create a new release once we implement all remaining jenkins integrations (1.1 maybe?) - so no version changes for now.

**Pull request merged**
